# Generated by Django 3.2.14 on 2022-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_text', models.CharField(max_length=200)),
                ('type_text', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('finish_time', models.DateTimeField(verbose_name='finish time')),
                ('details', models.CharField(max_length=500)),
            ],
        ),
    ]
