# Generated by Django 3.2.14 on 2022-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_venue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
