# Generated by Django 3.2.14 on 2022-07-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_auto_20220724_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='type_text',
        ),
    ]
