# Generated by Django 3.2.14 on 2022-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_remove_venue_type_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('LPN', 'Lpn'), ('RN', 'Rn')], default='RN', max_length=3),
        ),
    ]
