# Generated by Django 3.2.14 on 2022-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
